### PR TITLE
Pull request

### PR DESCRIPTION
**Pull request by AlbertoP57**
- updated select2-bootstrap.css to v0.1.0-beta.10

- select2's theme set to 'bootstrap' in 
\Classes\Utilities\JavaScriptBlock.cs
\Scripts\Forum\yaf.Main.js

- modified card output in jquery.hovercard.js
- modified cards-footer in topics.ascx

### CODE REVIEW

**Comment by w8tcha** [comment]
You pulled in the wrong select2 files. there are not compatible with boostrap 4. i added the missing files. can you apply the changes. then i can approve the request. or i pull it in manually

**Comment by AlbertoP57** [comment]
Pushed the "resolving conflict" button. The System seems blocked...
Anyway, there were select2.css files in a "css" folder. And compile was impossibile. I created a "select2" folder where I put the files downloaded directly from github. Its working good (compile and run) in my test area.

________________________________
Da: Ingo<mailto:notifications@github.com>
Inviato: ‎07/‎06/‎2019 11:42
A: YAFNET/YAFNET<mailto:YAFNET@noreply.github.com>
Cc: AlbertoP57<mailto:alberto.pasqualini@outlook.com>; Author<mailto:author@noreply.github.com>
Oggetto: Re: [YAFNET/YAFNET] Pull request (#426)


You pulled in the wrong select2 files. there are not compatible with boostrap 4. i added the missing files. can you apply the changes. then i can approve the request. or i pull it in manually

**Comment by AlbertoP57** [comment]
ok I got the reason:
Files Content\select2\* were missing and I got compilation error. I copied them from folder Content\css (you should remove them from repo).
 Then I had to change the "theme" (from bootstrap4 to bootstrap) in files 
\Classes\Utilities\JavaScriptBlock.cs
\Scripts\Forum\yaf.Main.js

And all was working good. Then I simply updated from internet the file select2-bootstrap to the last version. And push to github.

This is wrong.

To avoid confusion I suggest to:
delete the Content\css folder (I guess I cannot do it)
Download the original css file select2-bootstrap4.css (without renaming it ...) and put in the folder Content\select2 folder
Set the right theme (bootstrap4) in files \Classes\Utilities\JavaScriptBlock.cs and \Scripts\Forum\yaf.Main.js
Edit \Content\forum-admin.scss to work with "select2-bootstrap4" file

I could delete my previous commit and push the correct one. Or you decide what to do...

**Comment by w8tcha** [comment]
Im so lazy i manually made the changes. So your pull request was approved. Thanks again for your continuing work!

**Pull request closed without merging**
