### PR TITLE
updated some VS2017 configuration

### PR DESCRIPTION
**Pull request by AlbertoP57**
I restarted repo again ... 
updates:
1) if you use c# 7.0+ (7.1,2,3) you need to set lnguage to the latest minor version
2) the path to msbuild.exe is ...\MSBuild\**15.0**\Bin\MSBuild.exe

### CODE REVIEW

**Comment by w8tcha** [comment]
Did you test the build files? at least with visual studio 2019 it doesnt work its the wrong path

**Comment by AlbertoP57** [comment]
Of course I tested the build files. I am still using VS2017 pro (I have problems with git ... I cannot add problems with a new version of VS). With the previous build the command cannot reach msbuild.exe.
Maybe MS changed the path (again!!!).
Do not accept changes related to builds.bat. In the meantime I can look for a solution.
The language minor version in mandatory or it compiles with 7.0 and raises many errors.

Alberto
________________________________
Da: Ingo<mailto:notifications@github.com>
Inviato: ‎12/‎06/‎2019 17:45
A: YAFNET/YAFNET<mailto:YAFNET@noreply.github.com>
Cc: AlbertoP57<mailto:alberto.pasqualini@outlook.com>; Author<mailto:author@noreply.github.com>
Oggetto: Re: [YAFNET/YAFNET] updated some VS2017 configuration (#429)


Did you test the build files? at least with visual studio 2019 it doesnt work its the wrong path

**Comment by Zero2Cool** [comment]
I've been building the batch files without issue. I'm using VS2019 Enterprise.

**Comment by w8tcha** [comment]
Well we could add a separate batch file for visual studio 2017

**Comment by w8tcha** [comment]
Seems to be working now! Thanks

**Pull request merged**
