### PR TITLE
search functions

### PR DESCRIPTION
**Pull request by AlbertoP57**
- YafFormatMessage.cs avoid to format ascii emoticons (this is not a chat, ascii emoticons can false the post content. imho) 
- yaf.SearchResult.js loading alert stays till complete load

### CODE REVIEW

**Comment by w8tcha** [comment]
This needs Some Review!

Why did you disable the converting of Asccii Smilies? This would break the old Smilies

Also the extra modal hide function of the Search is needed in some cases. There is a reason why this code exist.

**Comment by AlbertoP57** [comment]
> 
> Why did you disable the converting of Asccii Smilies? This would break the old Smilies
> 
just check it ... (I mean EmojiOne.ShortnameToUnicode())

Old smilies are stored like this (i.e.): `[confused]`. The function `ShortnameToUnicode(string, false)` translates [confused] to a smiley **in any case**. 
 
The problem is the second second part of that function. If you use:
`EmojiOne.ShortnameToUnicode(string, true);`
it replaces sequence of chars based on a table. For example: `:D` to the correspondent smiley.  
This would break the messages ;)

Just create, in **your** (unmodified) environment, a post with this text:
`Note:Developers are crazy (without space between : and D)`
save it :D

Is it that what you want. Feel free to. You are the boss!

And worse. Suppose you have a message that contains this text:
<bold string 1>.<bold string 2>
The string `>.<` is treated like a smiley ... the whole page crashes.

> Also the extra modal hide function of the Search is needed in some cases. There is a reason why this code exist.

From the jquery [documentation](https://api.jquery.com/Ajax_Events/):

**success** (Local Event)
This event is only called if the request was successful (no errors from the server, no errors with the data).
**complete** (Local Event)
This event is called regardless of if the request was successful, or not. You will always receive a complete callback, even for synchronous requests.

To hide the modal window just when `success` event raises is useless. Anyway if: 
> There is a reason why this code exist.

just move the block of code at the end of the `success` section.

**Comment by w8tcha** [comment]
> Is it that what you want? Feel free to. You are the boss!

i understand the problem. But when a function doesn't work properly. The solution is not to remove the function, instead fix the function!

The solution would be to exclude ascii like :D and only include the old ones from the old smilies!

> The string >.< is treated like a smiley ... the whole page crashes.

No it s not because its not converted because the > are encoded

**Comment by w8tcha** [comment]
> To hide the modal window just when success event raises is useless.

Did you read my message above. i know the documentation. But in some cases i tested it doesn't work like it should. That's why the code exist.

**Comment by AlbertoP57** [comment]
> 
> The solution would be to exclude ascii like :D and only include the old ones from the old smilies!
> 
Today you exclude :D, tomorrow something other. And so on... Insert this text in a new post (standard bb code editor) and hit preview:
`[b]something bold[/b].[color=red]red color text[/color]`
look at the page. Are you sure in advance that a user does not enter a text like this one?

I guess that by the time Linus Birgerstam created EmojiOne C# class, he knew that the boolean parameter in the ShortnameToUnicode method would become useful to someone.

We could save the day by allowing the forum administrator to choose the option to activate/deactivate the ascii smiley conversion.
If you create the entry in the language file and a boolean field in the database (you are quicker for sure) I can modify the settings entry page.

If you don't agree at all ... well ... it doesn't matter ;)

**Comment by w8tcha** [comment]
No I agree with you. But removing the feature is not the solution. the easiest the solution would be to convert only when then ascci is only converted when its lead by a space and trailed with a space.

But I don't understand what other bbcodes have to do with that issue. That is a different issue.

**Pull request closed without merging**
